steps:
  # 1. Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast2-docker.pkg.dev/$PROJECT_ID/my-util-repo/hello-world-api-service:$COMMIT_SHA",
        ".",
      ]

  # 2. イメージを Artifact Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast2-docker.pkg.dev/$PROJECT_ID/my-util-repo/hello-world-api-service:$COMMIT_SHA",
      ]

  # 3. Secret Manager から認証キーを取得して Cloud Run にデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "hello-world-api-service" # あなたの Cloud Run サービス名
      - "--image=asia-northeast2-docker.pkg.dev/$PROJECT_ID/my-util-repo/hello-world-api-service:$COMMIT_SHA"
      - "--region=asia-northeast2" # あなたのリージョン
      - "--platform=managed"
      # ここで Secret Manager のシークレットを環境変数として設定
      # secrets: [{secret: シークレット名, env: 環境変数名}]
      # バージョンを指定しない場合は 'latest' が使われる
      - "--set-secrets=SECRET_AUTH_KEY=api-auth-key:latest"
      # 以前設定した未認証許可フラグ (必要に応じて)
      # '--allow-unauthenticated' # もし外部から直接呼び出す必要がある場合

# ビルドログのリージョン設定 (以前追加したもの)
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
