steps:
  # 1. Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast2-docker.pkg.dev/$PROJECT_ID/my-util-repo/hello-world-api-service:$COMMIT_SHA",
        ".",
      ]

  # 2. イメージを Artifact Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast2-docker.pkg.dev/$PROJECT_ID/my-util-repo/hello-world-api-service:$COMMIT_SHA",
      ]

  # 3. Secret Manager から認証キーを取得して Cloud Run にデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "hello-world-api-service" # あなたの Cloud Run サービス名
      - "--image=asia-northeast2-docker.pkg.dev/$PROJECT_ID/my-util-repo/hello-world-api-service:$COMMIT_SHA"
      - "--region=asia-northeast2" # あなたのリージョン
      - "--platform=managed"
      - "--set-secrets=SECRET_AUTH_KEY=api-auth-key:latest"
      - "--set-secrets=GOOGLE_GEN_AI_API_KEY=gemini-api-key:latest"
      - "--set-secrets=SLACK_TOKEN=slack-bot-token:latest"
      - "--set-secrets=SLACK_CHANNEL=slack-target-channel:latest"

# ビルドログのリージョン設定 (以前追加したもの)
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
